language: php
php:
  - 7.1
  - 7.2
  - 7.3

before_install:
  # Turn off XDebug
  - phpenv config-rm xdebug.ini || return 0

install:
  # Composer
  - travis_retry composer install --no-progress --prefer-dist

script:
  # Tests
  - vendor/bin/tester -s -p php --colors 1 ./tests/cases

after_failure:
  # Print *.actual content
  - for i in $(find tests -name \*.actual); do echo "--- $i"; cat $i; echo; echo; done

jobs:
  include:
    - env: title="Lowest Dependencies 7.1"
      php: 7.1
      install:
        - travis_retry composer update --no-progress --prefer-dist --prefer-lowest
      script:
        - vendor/bin/tester -s -p php --colors 1 ./tests/cases

    - stage: Quality Assurance
      php: 7.1
      script:
        - make ecs
        - make sensiolab

    - stage: Phpstan
      php: 7.1
      script:
        - make phpstan

    - stage: Test Coverage
      if: branch = master AND type = push
      php: 7.1
      script:
        - vendor/bin/tester -s -p phpdbg --colors 1 -C -d extension=xdebug.so --coverage ./coverage.xml --coverage-src ./src ./tests/cases
      after_script:
        - wget https://github.com/php-coveralls/php-coveralls/releases/download/v2.1.0/php-coveralls.phar
        - php php-coveralls.phar --verbose --config tests/config/.coveralls.yml

    - stage: Outdated Dependencies
      if: branch = master AND type = cron
      php: 7.1
      script:
        - composer outdated --direct --strict

  allow_failures:
    - stage: Test Coverage

sudo: false

cache:
  directories:
    - $HOME/.composer/cache
